import * as cheerio from 'cheerio';
import axios from 'axios';
import { Name } from 'mizzoureview-reading/models/name';
import {
    AIPromptAnswers,
    Professor,
} from 'mizzoureview-reading/models/professor';
import { generateWikiFunFacts } from 'src/helpers/gemini.js';

// first generated by chatgpt
export async function getArticleContentByName(name: Name) {
    const baseUrl = 'https://en.wikipedia.org/w/api.php';

    // Step 1: Search for the page
    const searchParams = new URLSearchParams({
        origin: '*',
        action: 'parse',
        page: `${name}`,
        format: 'json',
    });

    const fetchUrl = `${baseUrl}?${searchParams}`;

    const { data } = await axios.get(fetchUrl);

    if (data.error) {
        return 'No article';
    }
    const $ = cheerio.load(data.parse.text['*']);

    // Extract only the main content paragraphs
    const articleText = $('p').text();

    return articleText;
}

export async function setProfessorFunFacts(
    profArray: Professor[],
): Promise<boolean> {
    for (let i = 0; i < profArray.length; i++) {
        const prof: Professor = profArray[i];
        if (prof.basicInfo === undefined) {
            return false;
        }
        const article = await getArticleContentByName(prof.basicInfo.name);
        const funFacts = await generateWikiFunFacts(article);
        if (funFacts !== undefined) {
            if (prof.aIPromptAnswers === undefined) {
                prof.aIPromptAnswers = new AIPromptAnswers({
                    funFacts: funFacts,
                });
            } else {
                prof.aIPromptAnswers = new AIPromptAnswers({
                    funFacts: funFacts,
                    letterToProfessor: prof.aIPromptAnswers.letterToProfessor,
                    letterToStudent: prof.aIPromptAnswers.letterToStudent,
                });
            }
        }
    }
    return true;
}
