import * as cheerio from "cheerio"
// first generated by chatgpt
export async function getArticleContentByName(fname: string, lname: string) {
    const baseUrl = 'https://en.wikipedia.org/w/api.php';

    // Step 1: Search for the page
    const searchParams = new URLSearchParams({
        origin: '*',
        action: 'parse',
        page: `${fname} ${lname}`,
        format: 'json',
    });

    const fetchUrl = `${baseUrl}?${searchParams}`;
    const searchResponse = await fetch(fetchUrl);
    const searchData = await searchResponse.json();
    if (searchData.error){
        return "No article"
    }
    const $ = cheerio.load(searchData.parse.text["*"]);

    
    // Extract only the main content paragraphs
    const articleText = $('p').text() 

    return articleText;
}

