import * as cheerio from 'cheerio';
import axios from 'axios';
import { Name } from 'mizzoureview-reading/models/name';

// first generated by chatgpt
export async function getArticleContentByName(name: Name) {
    const baseUrl = 'https://en.wikipedia.org/w/api.php';

    // Step 1: Search for the page
    const searchParams = new URLSearchParams({
        origin: '*',
        action: 'parse',
        page: `${name}`,
        format: 'json',
    });

    const fetchUrl = `${baseUrl}?${searchParams}`;

    const { data } = await axios.get(fetchUrl);

    if (data.error) {
        return 'No article';
    }
    const $ = cheerio.load(data.parse.text['*']);

    // Extract only the main content paragraphs
    const articleText = $('p').text();

    return articleText;
}
